apiVersion: v1
kind: ConfigMap
metadata:
  name: bitpesa-config-staging
  namespace: bitpesa
data:
  NODE_ENV: "staging"
  LOG_LEVEL: "debug"
  API_VERSION: "v1"
  CORS_ORIGIN: "https://staging.bitpesa.com,http://localhost:3000"
  CORS_CREDENTIALS: "true"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX: "200"
  ENABLE_SWAGGER: "true"
  ENABLE_HEALTH_CHECK: "true"
  ENABLE_METRICS: "true"
  ENABLE_SECURITY_HEADERS: "true"
  ENABLE_HELMET: "true"
  ENABLE_COMPRESSION: "true"
  ENABLE_CORS: "true"
  ENABLE_RATE_LIMIT: "true"
  BODY_PARSER_LIMIT: "10mb"
  ENABLE_COOKIE_PARSER: "true"
  ENABLE_SESSION: "true"
  SESSION_MAX_AGE: "86400000"
  ENABLE_CSRF: "true"
  ENABLE_HSTS: "false"
  HSTS_MAX_AGE: "31536000"
  ENABLE_XSS_PROTECTION: "true"
  ENABLE_NO_SNIFF: "true"
  ENABLE_FRAME_OPTIONS: "true"
  FRAME_OPTIONS_VALUE: "SAMEORIGIN"
  ENABLE_CONTENT_TYPE_OPTIONS: "true"
  ENABLE_REFERRER_POLICY: "true"
  REFERRER_POLICY_VALUE: "strict-origin-when-cross-origin"
  ENABLE_PERMISSIONS_POLICY: "true"
  PERMISSIONS_POLICY_VALUE: "camera=(), microphone=(), geolocation=()"
  # Staging specific
  MPESA_ENVIRONMENT: "sandbox"
  LND_NETWORK: "testnet"
  DATABASE_POOL_MIN: "2"
  DATABASE_POOL_MAX: "5"
  REDIS_DB: "1"
  MONGODB_DATABASE: "bitpesa_staging"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitpesa-config-production
  namespace: bitpesa
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_VERSION: "v1"
  CORS_ORIGIN: "https://bitpesa.com"
  CORS_CREDENTIALS: "true"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX: "100"
  ENABLE_SWAGGER: "false"
  ENABLE_HEALTH_CHECK: "true"
  ENABLE_METRICS: "true"
  ENABLE_SECURITY_HEADERS: "true"
  ENABLE_HELMET: "true"
  ENABLE_COMPRESSION: "true"
  ENABLE_CORS: "true"
  ENABLE_RATE_LIMIT: "true"
  BODY_PARSER_LIMIT: "10mb"
  ENABLE_COOKIE_PARSER: "true"
  ENABLE_SESSION: "true"
  SESSION_MAX_AGE: "86400000"
  ENABLE_CSRF: "true"
  ENABLE_HSTS: "true"
  HSTS_MAX_AGE: "31536000"
  ENABLE_XSS_PROTECTION: "true"
  ENABLE_NO_SNIFF: "true"
  ENABLE_FRAME_OPTIONS: "true"
  FRAME_OPTIONS_VALUE: "DENY"
  ENABLE_CONTENT_TYPE_OPTIONS: "true"
  ENABLE_REFERRER_POLICY: "true"
  REFERRER_POLICY_VALUE: "strict-origin-when-cross-origin"
  ENABLE_PERMISSIONS_POLICY: "true"
  PERMISSIONS_POLICY_VALUE: "camera=(), microphone=(), geolocation=()"
  # Production specific
  MPESA_ENVIRONMENT: "production"
  LND_NETWORK: "mainnet"
  DATABASE_POOL_MIN: "5"
  DATABASE_POOL_MAX: "20"
  REDIS_DB: "0"
  MONGODB_DATABASE: "bitpesa_production"
