global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kong API Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Compliance Service
  - job_name: 'compliance-service'
    static_configs:
      - targets: ['compliance-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Monitoring Service
  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Lightning Service
  - job_name: 'lightning-service'
    static_configs:
      - targets: ['lightning-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # M-Pesa Service
  - job_name: 'mpesa-service'
    static_configs:
      - targets: ['mpesa-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Transaction Service
  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Conversion Service
  - job_name: 'conversion-service'
    static_configs:
      - targets: ['conversion-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Receipt Service
  - job_name: 'receipt-service'
    static_configs:
      - targets: ['receipt-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Rate Limit Service
  - job_name: 'rate-limit-service'
    static_configs:
      - targets: ['rate-limit-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # LND
  - job_name: 'lnd'
    static_configs:
      - targets: ['lnd:8080']
    metrics_path: '/v1/metrics'
    scrape_interval: 30s

  # Bitcoin Core
  - job_name: 'bitcoind'
    static_configs:
      - targets: ['bitcoind:18332']
    scrape_interval: 60s
