apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: bitpesa
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mpesa-service
  namespace: bitpesa
  labels:
    app: mpesa-service
spec:
  selector:
    app: mpesa-service
  ports:
  - name: http
    port: 80
    targetPort: 3002
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: bitpesa
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
  - name: http
    port: 80
    targetPort: 3003
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: bitpesa
  labels:
    app: monitoring-service
spec:
  selector:
    app: monitoring-service
  ports:
  - name: http
    port: 80
    targetPort: 3004
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: receipt-service
  namespace: bitpesa
  labels:
    app: receipt-service
spec:
  selector:
    app: receipt-service
  ports:
  - name: http
    port: 80
    targetPort: 3005
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rate-limit-service
  namespace: bitpesa
  labels:
    app: rate-limit-service
spec:
  selector:
    app: rate-limit-service
  ports:
  - name: http
    port: 80
    targetPort: 3006
    protocol: TCP
  type: ClusterIP
