apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: bitpesa
  labels:
    app: auth-service
    service: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        service: auth
    spec:
      containers:
      - name: auth-service
        image: bitpesa/auth-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: bitpesa-config
              key: NODE_ENV
        - name: PORT
          value: "3001"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: bitpesa-config
              key: LOG_LEVEL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bitpesa-secrets
              key: JWT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: bitpesa-secrets
              key: SESSION_SECRET
        - name: POSTGRES_URL
          value: "postgresql://bitpesa_user:$(POSTGRES_PASSWORD)@postgres:5432/bitpesa"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitpesa-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@redis:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitpesa-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bitpesa
  labels:
    app: auth-service
    service: auth
spec:
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
