apiVersion: v1
kind: ConfigMap
metadata:
  name: bitpesa-config
  namespace: bitpesa
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_VERSION: "v1"
  CORS_ORIGIN: "https://bitpesa.com"
  CORS_CREDENTIALS: "true"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX: "100"
  ENABLE_SWAGGER: "false"
  ENABLE_HEALTH_CHECK: "true"
  ENABLE_METRICS: "true"
  ENABLE_SECURITY_HEADERS: "true"
  ENABLE_HELMET: "true"
  ENABLE_COMPRESSION: "true"
  ENABLE_CORS: "true"
  ENABLE_RATE_LIMIT: "true"
  BODY_PARSER_LIMIT: "10mb"
  ENABLE_COOKIE_PARSER: "true"
  ENABLE_SESSION: "true"
  SESSION_MAX_AGE: "86400000"
  ENABLE_CSRF: "true"
  ENABLE_HSTS: "true"
  HSTS_MAX_AGE: "31536000"
  ENABLE_XSS_PROTECTION: "true"
  ENABLE_NO_SNIFF: "true"
  ENABLE_FRAME_OPTIONS: "true"
  FRAME_OPTIONS_VALUE: "DENY"
  ENABLE_CONTENT_TYPE_OPTIONS: "true"
  ENABLE_REFERRER_POLICY: "true"
  REFERRER_POLICY_VALUE: "strict-origin-when-cross-origin"
  ENABLE_PERMISSIONS_POLICY: "true"
  PERMISSIONS_POLICY_VALUE: "camera=(), microphone=(), geolocation=()"
